### ISSUE TITLE
Freeleech / VIP tags?

### ISSUE THREAD

**Issue by Zipties** [MangoScango/autodl-chatzilla#2]
This is a question not an issue, so I apologize if this isn't the right forum for it. But, I was wondering if it was possible to specify only VIP or FL torrents like in autodl-irrsi.

![image](https://user-images.githubusercontent.com/11506166/74456909-1df0f380-4e4d-11ea-8506-0bf5daab7314.png)

**Comment by MangoScango** [comment]
Unfortunately, I think these are just one of quite a few of the tags that this plugin was never updated to support. The only way I know how to catch freeleech is if they are in the release name, like so:

![image](https://user-images.githubusercontent.com/7623678/74467609-61f0f200-4e67-11ea-84e6-58cded2b918f.png)

I would like to add that, however it's currently beyond the scope of my understanding of the original project to implement more tags.

In addition to this, with FireFox no longer supporting the old extension API, ChatZilla appears to not be in development. Meaning we're stuck with old FireFox versions, so the maintainability of this project is already pretty limited. So unfortunately, I'm not really willing to spend the time needed to learning the codebase enough to implement missing features like this, as ChatZilla is kind of a dead end. I would sooner spend that time working on a new plugin for a more maintainable IRC client.

**Comment by Zipties** [comment]
> In addition to this, with FireFox no longer supporting the old extension API, ChatZilla appears to not be in development. Meaning we're stuck with old FireFox versions, so the maintainability of this project is already pretty limited. So unfortunately, I'm not really willing to spend the time needed to learning the codebase enough to implement missing features like this, as ChatZilla is kind of a dead end. I would sooner spend that time working on a new plugin for a more maintainable IRC client.

Ah, I wasn't aware of that. Thank you for the insight there.
