### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by Squirrel07** [MangoScango/autodl-chatzilla#3]
Add regex to filter options would be nice.
And support for 4k content.

I dont know if i created a pull request yestoday, i am sorry i am new to github, and dont know exatly how to communitate with the dev :( but i hope these features get added, this plugin is still very valid option for auto dl, i use it all the time :)

**Comment by MangoScango** [comment]
This project is no longer maintaned. Check out https://github.com/autobrr/autobrr
