### ISSUE TITLE
Found a working version, this one does not work

### ISSUE THREAD

**Issue by L0garithmic** [MangoScango/autodl-chatzilla#4]
https://github.com/robert022/autodl-chatzilla
The autodl-chatzilla on github, by robert022, works with ChatZilla 0.9.92 on XULRunner.

**Comment by JmMndz** [comment]
Hello @L0garithmic, I couldn't find a better way to contact you. I read your comment or request here https://github.com/juh9870/EXpandableFolder
You might find this interesting for you: https://forum.rainmeter.net/viewtopic.php?t=41394

**Comment by MangoScango** [comment]
FYI this was working fine for me, but I would recommend checking out autobrr.

https://github.com/autobrr/autobrr
